### ISSUE TITLE
The commit messages start with a new line character

### ISSUE THREAD

**Issue by IonicaBizau** [yorkie/node-gitlog-parser#2]
I guess that's a little bug.

**Comment by IonicaBizau** [comment]
![image](https://cloud.githubusercontent.com/assets/2864371/8566106/52884ee8-2564-11e5-8539-49b8de1619b8.png)

**Comment by yorkie** [comment]
Thanks for your report @IonicaBizau, this is actually because the `:` in message, and also I include a test case at https://github.com/yorkie/node-gitlog-parser/blob/master/sample.log#L14-L20 :)

**Comment by IonicaBizau** [comment]
@yorkie Nice! :+1: Thanks a lot.
